### ISSUE TITLE
Can be added some functions to L1/L2/R1/R2?

### ISSUE THREAD

**Issue by dontsnm** [waldnercharles/Minimis#6]
Can be added some functions to L1/L2/R1/R2?

L1/R1: Scroll page up / Scroll page down
L2/R2: Previous system / Next system

**Comment by waldnercharles** [comment]
Yep, this is on my todo and should be pretty trivial to add.

**Comment by waldnercharles** [comment]
Added with eba7337efccc0b8a52233ae330d59c8b9b306c6d.
