### ISSUE TITLE
[Bug] I cannot see more than 13 systems in the menu list

### ISSUE THREAD

**Issue by dontsnm** [waldnercharles/Minimis#7]
I cannot see more than 13 systems in the menu list. The menu list is not scrolling to watch more systems.

This is a example. Gameboy system not appear in the list:

![photo_5947418262369318877_y](https://user-images.githubusercontent.com/45759713/196959651-ed19146b-5e49-4eed-b3b2-4dc4367fbf28.jpg)

**Comment by waldnercharles** [comment]
Thanks for the bug report. I'll look into this soon.

**Comment by waldnercharles** [comment]
Fixed with c4cb799c1bb5327e84d82f417ef914b6d6866dd5
