### ISSUE TITLE
Feature request: move to row below regardless of current column

### ISSUE THREAD

**Issue by denisidoro** [waldnercharles/Minimis#9]
First of all, thank you for providing such an awesome theme ♥

Not sure if this is a bug or if this is something you have control over in your theme.

Let's say that I'm currently in column=3 but the next row has only one item. If I press down nothing happens. If I move to the first column then press down, it works.

**Comment by waldnercharles** [comment]
Good idea. Just added with aeeccc54b45f957fa320d7897930cc558a428090.
